name: GasBuddy Daily Notifier

on:
  schedule:
    # GitHub cron is in UTC. EST = UTC-5 (winter), EDT = UTC-4 (summer)
    # Example here uses EDT (UTC-4). Adjust if needed.
    - cron: "0-59 10-2 * * *"   # every minute from 6AM-11PM EST/EDT
  workflow_dispatch:            # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager schedule

      - name: Run script
        run: python gasbuddy_email.py
